language:
  - python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    - "3.8-dev"  # 3.8 development branch
    - "nightly"  # nightly build
      # https://blog.travis-ci.com/2018-10-11-windows-early-release
  allow_failure:
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode11  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install:
        python3 --version ; pip3 --version ; sw_vers
  #   - name: "Python 3.7.4 on Windows"
  #     os: windows           # Windows 10.0.17134 N/A Build 17134
  #     language: shell       # 'language: python' is an error on Travis CI Windows
  #     # python: 3.7         # 'python:' is ignored on Travis CI Windows
  #     before_install:
  #       - choco install python  # this install takes at least 1 min 30 sec
  #       - python3 -m pip install --upgrade pip
  #     env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
#install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
#
notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install --upgrade pip
  - pip install . #pip install --upgrade pip
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt
env:
  global:
    # Doctr deploy key for vstadnytskyi/auxiliary
    - secure: "X/gFuf8yXnk5zTQ//OzK6OxO3vOWFnEHF++WI+MrAjX3Vib+Bf3Mv46ZON7UYV9VDoj63UF+VPe0qFOdcjcYkKRfa7HH+cnpMcd6wf8dVOf8f/nV5S5trhL2IGiOfiVwWGlRn5b3Iay1uk5PjEDpCHVWijU1kAUfa4rstyM1jDRbuTxPIrNXj3GwaAMt0rdpls/7+TEKB9aSxut32FCECm6XcUKy9N7IDekwr8IE/a29HNgJjUFfw/T1M58ioWN5zABwJj9/Wt7udAgJEZHRyIAavF6BDGqlnrGHjCi3K8JvtvRLkb0iOHI1XGO3AcaH9XWgOGrYQudDFlK39K4MUTbGdoNk63cj+lEryJxuQSIN3Gxuqapk2ByTMQuTBXvGMw04AoER79dZvb971tJe/pyUmSjMp5aAGsL+akV6xjfdK7Omzf1qFCoUouLjBOXR4PoiiUZaeSKkt0qEILmVQH5blxiMXj4F4c8rEkUm2JaLsF9UW5cJvTRGImJfQFUW9m4RQwsvA/OXL+Cr44RXVNFNWuJTPz3Mklmi6ZKd+YEjU/5N4MBeUM8RtCM+ytwnicE6fwF1LiWG6Vs/90921aTsPNYZxBZjAhoYuBezv6VbXEikZEkfvddI3YEaFjYIzEdYBWctDR6J+XatkrfYLUMk+jjnXpLfJMnlRzgHwTo="
script:
#  - python3 platform-info.py || python platform-info.py
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
#  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - set -e  # If any of the following steps fail, just stop at that point.
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .  # Publish the documentation.
